### Spring
spring:
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:postgresql://localhost:55432/postgres?user=postgres&password=123456}
    driver-class-name: org.postgresql.Driver
  security:
    user:
      name: ${ADMIN:admin}
      password: ${ADMIN_PW:}

server:
#  servlet:
#    session:
#      cookie:
#        name: SESSION
  compression:
    enabled: true
  port: ${PORT:8080}

#profiles:
ansible:
  path: ${ANSIBLE_PATH:/app/ansible}

management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  file:
    path: log