AWSTemplateFormatVersion: "2010-09-09"
Description: anti-GFW server

Parameters:
  LightsailName:
    Type: String
  DomainName:
    Type: String
  Password:
    Type: String
Resources:
  Lightsail:
    Type: AWS::Lightsail::Instance
#    CreationPolicy:
#      ResourceSignal:
#        Timeout: PT10M # Specify the time here
    Properties:
      BlueprintId: amazon_linux_2
      BundleId: nano_2_0
      InstanceName:
        Ref: LightsailName
      AvailabilityZone: ap-northeast-1a
      Networking:
        Ports:
          - FromPort: 443
            ToPort: 443
          - FromPort: 80
            ToPort: 80
          - FromPort: 22
            ToPort: 22

  LightsailIp:
    Type: AWS::Lightsail::StaticIp
    Properties:
      AttachedTo:
        Ref: Lightsail
      StaticIpName: !Sub "${LightsailName}-ip"

Outputs:
  LightsailIp:
    Description: LightsailIp
    Value: !GetAtt LightsailIp.IpAddress