---
- hosts: all
  become: yes

  tasks:
    - name: yum update
      yum: 
        name: '*'
        state: latest
    
    - name: install nginx
      shell: |
        amazon-linux-extras install -y nginx1

    - name: Enable nginx
      service: name=nginx state=started enabled=yes